# This is a basic workflow that is manually triggered

name: marketplace

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [linux]
    name: marketplace ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          go mod download
          cd cmd/marketplaced
          go build .
      - uses: actions/upload-artifact@v2
        with:
          name: marketplaced ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/marketplaced/marketplaced